### ISSUE TITLE
implement /follow target

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#24]
89fdc94dfc11bb6cccc03ac721be89cb025034b5

**Comment by plague006** [comment]
The implementations of following that I have seen have all felt bad since the camera is very jerky. Is the idea to be able to find a player quickly and track their actions?

Or is this meant as a general player feature similar to the /follow command in MMOs like WoW where it just sets you to automatically walk with another player?

**Comment by Valansch** [comment]
Old issue, see referenced commit
