### ISSUE TITLE
Four Quadrants - Each quadrant produces different things and feeds each-other

### ISSUE THREAD

**Issue by Hexicube** [Valansch/RedMew#714]
Relatively simple premise. There are four quadrants to the map, with a large void divider (horizontal and vertical) that intersects the map center.

Either the divider would be sufficiently thick to prevent roboport coverage reaching the other side, with belts as the transfer medium, or it would be 4 tiles thick allowing players to direct transfer across the void and create undergrounds where needed instead of in preset locations.

Each quadrant would have a different set of recipe restrictions, so that all four quadrants are required to get anything done.

All quadrants would have access to "vital" recipes, such as inserters, mining drills, furnaces. This is to ensure a quadrant can get set up without relying on another quadrant.

Everything else is distributed to quadrants, possibly randomly, to force exchanging products. Green circuit recipes might only be available to the left two quadrants, whilst red circuits are only available to the bottom-right quadrant.

**Comment by SimonFlapse** [comment]
Interesting idea. I'm thinking:

* Spacing between quadrants must be greater than the reach of a roboport
* Transport of items between two quadrants should be with underground belts to prevent players from just walking over. 
* Could prevent transfer of power network too.

I like the idea of disabling recipes for the quadrants making them dependant on each other.

I'm thinking that we spawn players in quadrant 1 but let them switch if they have an empty inventory (Excluding armor?) The switching could be a simple GUI where you pick side or an CLI command.

I have previously seen players roleplay different factions and this will kind of promote this without throwing away the teamwork aspect.

Great suggestion! Thanks for putting in the time to explain the idea, really helps us move forward with it.

**Comment by SimonFlapse** [comment]
I have created a mock mapgen for this idea
![image](https://user-images.githubusercontent.com/44922798/52008110-415e3000-24d0-11e9-86f9-cb54b5da85ad.png)

![image](https://user-images.githubusercontent.com/44922798/52008129-4e7b1f00-24d0-11e9-87b7-45b97288f3c5.png)


Allows fast underground belts to transverse between quadrants and preventing logistic networks from connecting, bridges every 4th tile.

Further additions:

Each quadrant should have it's own starting resources, and players will be on their own force, allowing for changing the available recipes for each quadrant.

Since it's supposed to focus on teamwork´, research should be shared (synced on_research_finished), I'm thinking of only letting quadrant 1 (top right) craft labs.

Ways to switch quadrant. Possible only with empty inventory to prevent people carrying over uncraftable items.

Ideas:

Instead of having "bridges" along the entire map, we could limit it to the first 2-4 chunks (16 - 32 bridges). I don't think throughput will get hurt much this way.

**Comment by SimonFlapse** [comment]
Made four identical spawns to ensure every quadrant has access to the basic raw materials needed.
![image](https://user-images.githubusercontent.com/44922798/52018461-cb1af700-24ea-11e9-83b4-7cbb0cabee11.png)

Also changed the "bridges" to tutorial-grid, thus removing it from the map view.

**Comment by Hexicube** [comment]
You need to be careful with those bridges, it looks like you can't reach far enough to place up to the halfway point by hand so there would need to be a few pre-placed ones to be used until construction bots.

You could also have 1 tile wide strips with a 4 tile gap in them, which would remove that requirement and allow manual trading without allowing logistics connections.

**Comment by adrianvanderwal** [comment]
> You could also have 1 tile wide strips with a 4 tile gap in them, which would remove that requirement and allow manual trading without allowing logistics connections.

Personally I think this would be a better solution.

> Could prevent transfer of power network too.

Isn't there a way to set those "bridges" to be a specific type of tile, which doesn't allow placement of anything but belts?

**Comment by SimonFlapse** [comment]
No specific tile that does, but we are able to check if an entity is created on the bridges, and disallow it if it's power. I haven't made much progress on a initial version since I haven't had a lot of time. If anyone is interested in contributing I can start up a PR for it.

**Comment by SimonFlapse** [comment]
Based on your feedback I changed the "bridges" to allow a yellow belt (and up) connection.
![image](https://user-images.githubusercontent.com/44922798/52915613-9f638380-32d6-11e9-817d-b30e06ffb5fc.png)

You can only built belts, splitter or underground belts on the tutorial tiles, preventing energy link and logistic network links.

Maybe we should allow train stuff, inserters and chests on tutorial tiles too.

Currently I just need to deside which restriction we should put on each quadrant.

Quadrant 1 (Top right) is the only one allowed to research (Shared between all quadrants)

**Comment by adrianvanderwal** [comment]
>Currently I just need to deside which restriction we should put on each quadrant.

Some suggestions:

> Quadrant 1 (Top right) is the only one allowed to research (Shared between all quadrants)

Quadrant 2 (Bottom Right) Mining - think, extremely rich patches close to the centre of the map, encourages players to mine in this quadrant and ship it to Q3

Quadrant 3 (Bottom Left) Smelting, Basic Intermediates (Gears, Copper Cables, Green Circuits) - Is there some way to increase the productivity of assemblers in this area?

Quadrant 4 (Top Left) Oil Processing and Rocket Parts

**Comment by SimonFlapse** [comment]
I disabled all recipes for all four quadrants and added the recipes shown in this document:
https://github.com/Refactorio/RedMew/blob/6d0df6a0fae9180569bf1b067fcc22d59d3f4a0b/map_gen/maps/quadrants/enabled_recipes.lua

This results in:
- Q1 being science and military
- Q2 being intermediate products (Steel, all circuits, engines) I like your idea of having this area being - preferred for mining, I'll keep it in mind since the implementation might take some time
- Q3 being oil and high tech (Nuclear, beacons, modules)
- Q4 being logistics (belts, bots, train)

**Comment by SimonFlapse** [comment]
I've added a boost in ore count for Q2. Thanks for the suggestion. Q2 had a rather lacking purpose if you exclude circuitry and steel.

**Comment by adrianvanderwal** [comment]
> Q4 being logistics (belts, bots, train)

That kinda doesn't make any sense though...
I mean, an entire quadrant for making belts, bots and trains?
Unless, there's a hidden "go out and find caches of b.b.t."...

Else, what is the purpose of Q4, besides being restrictive?

That is, unless I misunderstand.

**Comment by SimonFlapse** [comment]
The quadrant is the only one being able to craft logistic items like belts, bots, trains and inserters. You then need to send it to the other quadrants unless they want to use burner inserters only. Each quadrant can mine resources like usual, and place all entities. Only exception is that labs only work in Q1
