### ISSUE TITLE
Land fill and diggy

### ISSUE THREAD

**Issue by AndrewTru** [Valansch/RedMew#964]
I don't know why, but the land fill tech is not re searchable in the scenario.
If you disabled it for some idea, I like to know.
Land fill is not over powered, it just allows us to change the water into land.
I have had times where I have to mess up my grid pattern due to a water pool.
You can tell I am a little OCD.
Not an issue per say, just a information request.

**Comment by SimonFlapse** [comment]
Diggy is developed with Multiplayer in mind, this exposes us to a huge griefing risk from landfill because water is limited, thus it's disabled by default. You should be able to buy landfill in the market for a *steep* price. You can always enable landfill in the diggy configuration:
https://github.com/Refactorio/RedMew/blob/da4827ea98fe2fe7e787a44f70aa86d441e8f4b8/map_gen/maps/diggy/config.lua#L61

**Comment by AndrewTru** [comment]
thanks for the info, I am mostly doing it with just me so grieving is not an issue.
Is there an in-game way to change the config or will I need to deep dive the code?

**Comment by SimonFlapse** [comment]
The following command can be executed in the LUA Console (Same as the one you use for chat) to enable landfill for the player force:
`/dc game.forces['player'].technologies['landfill'].enabled = true`

**Comment by AndrewTru** [comment]
So if I did this command do I just put player or my name in the game?

**Comment by SimonFlapse** [comment]
You leave it as it is

**Comment by AndrewTru** [comment]
thanks for the info, will keep that in mind for the next play time.
